# Generated by Django 3.2.1 on 2021-05-06 17:12

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=200, verbose_name="email")),
                (
                    "pincode",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(100000),
                            django.core.validators.MaxValueValidator(999999),
                        ],
                        verbose_name="pincode",
                    ),
                ),
                (
                    "district_id",
                    models.IntegerField(blank=True, null=True, verbose_name="district"),
                ),
                (
                    "age_limit",
                    models.IntegerField(
                        choices=[(18, "18+"), (45, "45+")],
                        default=(18, "18+"),
                        verbose_name="age limit",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "last_mail_sent",
                    models.DateTimeField(auto_now_add=True, verbose_name="last_mail"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created_date"
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="updated_date"),
                ),
            ],
        ),
    ]
