# Generated by Django 3.2.1 on 2021-05-08 09:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0001_subscriber_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="email",
            field=models.EmailField(
                blank=True, max_length=200, null=True, verbose_name="email"
            ),
        ),
    ]
