# Generated by Django 3.2.1 on 2021-05-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0002_subscriber_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="daily_sms_count",
            field=models.IntegerField(default=0, verbose_name="daily sms count"),
        ),
    ]
