# Generated by Django 3.2.1 on 2021-05-13 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0003_subscriber_daily_sms_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="last_mail_sent",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, verbose_name="last_mail"
            ),
        ),
    ]
