# Generated by Django 3.2.1 on 2021-05-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0004_last_mail_time_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="age_limit",
            field=models.IntegerField(
                choices=[(18, "18+"), (45, "45+")], default=18, verbose_name="age limit"
            ),
        ),
    ]
