# Generated by Django 3.2.1 on 2021-05-21 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0005_alter_subscriber_age_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="age_limit",
            field=models.IntegerField(
                choices=[(18, "18 and older"), (45, "45 and older")],
                default=18,
                help_text="Select your age category",
                verbose_name="age limit",
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="district_id",
            field=models.IntegerField(
                blank=True,
                help_text="Districts are based on voting districts",
                null=True,
                verbose_name="district",
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="pincode",
            field=models.IntegerField(
                blank=True,
                help_text="Don't know your pincode? Use 'By District'",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100000),
                    django.core.validators.MaxValueValidator(999999),
                ],
                verbose_name="pincode",
            ),
        ),
    ]
