name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Database Setup
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'
        postgresql db: db
        postgresql user: dbuser
        postgresql password: dbpass
    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: 5
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DEBUG: 1
        SECRET_KEY: foo
        DJANGO_ALLOWED_HOSTS: "*"
        SQL_ENGINE: django.db.backends.postgresql_psycopg2
        SQL_DATABASE: db
        SQL_USER: dbuser
        SQL_PASSWORD: dbpass
        SQL_HOST: localhost
        SQL_PORT: 5432
        SNIFFING_INTERVAL_SECONDS: 300
        MAIL_COOLDOWN_SECONDS: 1800
        DOMAIN: "http://localhost:8000"
        CELERY_BROKER_URL: "redis://localhost:6379"
      run: |
        python manage.py test
