name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Database Setup
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'
        postgresql db: db
        postgresql user: dbuser
        postgresql password: dbpass
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DEBUG: 1
        SECRET_KEY: foo
        DJANGO_ALLOWED_HOSTS: "*"
        SQL_DATABASE: db
        SQL_USER: dbuser
        SQL_PASSWORD: dbpass
        SQL_HOST: localhost
        SQL_PORT: 5432
      run: |
        python manage.py test
